- name: Préparer l'environnement Apache pour héberger WordPress
  hosts: webserver
  become: yes

  # Préparations de l'environnement
  pre_tasks:
    - name: Créer le répertoire document root pour WordPress
      file:
        path: "/var/www/wordpress"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

  vars:
    # Port principal d'Apache
    apache_listen_port: 80

    # mail administrateur
    apache_server_admin: webmaster@example.com

    # modules additionnels WordPress
    apache_additional_modules:
      - rewrite
      - headers

    # Configuration VirtualHosts Apache
    apache_vhosts:
      - servername: 'wordpress.example.com'
        server_aliases:
          - www.wordpress.example.com
        document_root: '/var/www/wordpress'
        access_log: '/var/log/apache2/wordpress_access.log'
        error_log: '/var/log/apache2/wordpress_error.log'
        extra_parameters: |
          <Directory "/var/www/wordpress">
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>

    #variables pour customiser le rôle

  roles:
    - geerlingguy.apache
