- name: Préparer l'environnement Apache pour héberger WordPress
  hosts: webservers
  become: yes

  # Préparations de l'environnement
  pre_tasks:
    - name: Créer le répertoire document root pour WordPress
      file:
        path: "/var/www/wordpress"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

  vars:
    # Port principal d'Apache
    apache_listen_port: 80

    # mail administrateur
    apache_server_admin: webmaster@example.com

    # modules additionnels WordPress
    apache_additional_modules:
      - rewrite
      - headers

    # Configuration VirtualHosts Apache
    apache_vhosts:
      - servername: "{{ ansible_default_ipv4.address }}" # Recup ip auto
        document_root: "/var/www/wordpress"              # Doit correspondre au pre_task

    #variables pour customiser le rôle

  roles:
    - geerlingguy.apache
