- hosts: webservers
  become: true
  gather_facts: false

  tasks:
    - name: Extraire les noms des clients pour ce serveur
      set_fact:
        client_names: "{{ client_users | map(attribute='name') | list }}"

    - name: Télécharger WordPress archive
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
        mode: '0644'

    - name: Installer unzip
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Décompresser WordPress pour chaque client
      ansible.builtin.command:
        cmd: unzip /tmp/wordpress.zip -d /var/www/{{ item }}
      args:
        creates: /var/www/{{ item }}/wordpress
      loop: "{{ client_names }}"

    - name: Déplacer le contenu wordpress/ à la racine pour chaque client
      ansible.builtin.shell: |
        mv /var/www/{{ item }}/wordpress/* /var/www/{{ item }}/
        rm -rf /var/www/{{ item }}/wordpress
      args:
        executable: /bin/bash
      loop: "{{ client_names }}"

    - name: Appliquer les permissions pour chaque client
      ansible.builtin.file:
        path: /var/www/{{ item }}
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      loop: "{{ client_names }}"
