- hosts: webserver1
  become: true

  tasks:
    - name: Télécharger WordPress archive
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
        mode: '0644'

    - name: Installer unzip
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Décompresser sans créer le dossier wordpress/
      ansible.builtin.command:
        cmd: unzip /tmp/wordpress.zip -d /var/www/client1
      args:
        creates: /var/www/client1/wordpress

    - name: Déplacer le contenu de wordpress/ à la racine
      ansible.builtin.shell: |
        mv /var/www/client1/wordpress/* /var/www/client1/
        rm -rf /var/www/client1/wordpress
      args:
        executable: /bin/bash

    - name: Appliquer les permissions
      ansible.builtin.file:
        path: /var/www/client1
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
