- hosts: webserver1
  become: true
  tasks:
    - name: Download WordPress archive
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
        mode: '0644'
